apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: notebook
      type: openclaw
      enabled: true
      image: quay.io/rh-ai-quickstart/openclaw-openshell:latest
      providers:
        - nvidia
      harnessRef:
        name: ds-default
        digest: sha256:9bf096867817a62c4793a0aff80b07b081ffd1fb48ebc6907d4296cba9e181d9
    - name: cuda-sandbox
      type: nemoclaw
      enabled: false
      agent: openclaw
      image: quay.io/rh-ai-quickstart/nemoclaw-sandbox:latest
      providers:
        - nvidia
    - name: toolbox
      type: generic
      enabled: false
      image: base
      providers:
        - nvidia
