apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: mail-proxy
      type: generic
      enabled: true
      image: base
      providers:
        - mail-read
